apiVersion: v1
kind: Service
metadata:
  name: {{ include "dentalcare.fullname" . }}-backend
  labels:
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: backend
