"""Add performance indexes on unindexed foreign keys.

Revision ID: 20260909_0016
Revises: 20260909_0015
Create Date: 2026-09-09 13:45:00.000000
"""

from alembic import op

revision = "20260909_0016"
down_revision = "20260909_0015"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_index("ix_ai_audit_logs_patient_id", "ai_audit_logs", ["patient_id"], if_not_exists=True)
    op.create_index("ix_ai_audit_logs_user_id", "ai_audit_logs", ["user_id"], if_not_exists=True)
    op.create_index("ix_ai_recommendations_appointment_id", "ai_recommendations", ["appointment_id"], if_not_exists=True)
    op.create_index("ix_ai_recommendations_dentist_id", "ai_recommendations", ["dentist_id"], if_not_exists=True)
    op.create_index("ix_ai_recommendations_reviewed_by_id", "ai_recommendations", ["reviewed_by_id"], if_not_exists=True)
    op.create_index("ix_ai_recommendations_treatment_id", "ai_recommendations", ["treatment_id"], if_not_exists=True)
    op.create_index("ix_appointment_timeline_events_actor_id", "appointment_timeline_events", ["actor_id"], if_not_exists=True)
    op.create_index("ix_appointments_rescheduled_from_id", "appointments", ["rescheduled_from_id"], if_not_exists=True)
    op.create_index("ix_attendance_records_clinic_id", "attendance_records", ["clinic_id"], if_not_exists=True)
    op.create_index("ix_attendance_records_organization_id", "attendance_records", ["organization_id"], if_not_exists=True)
    op.create_index("ix_departments_head_dentist_id", "departments", ["head_dentist_id"], if_not_exists=True)
    op.create_index("ix_employee_documents_employee_id", "employee_documents", ["employee_id"], if_not_exists=True)
    op.create_index("ix_employee_incentives_approved_by", "employee_incentives", ["approved_by"], if_not_exists=True)
    op.create_index("ix_employee_incentives_employee_id", "employee_incentives", ["employee_id"], if_not_exists=True)
    op.create_index("ix_employee_training_records_course_id", "employee_training_records", ["course_id"], if_not_exists=True)
    op.create_index("ix_employee_training_records_employee_id", "employee_training_records", ["employee_id"], if_not_exists=True)
    op.create_index("ix_employees_clinic_id", "employees", ["clinic_id"], if_not_exists=True)
    op.create_index("ix_employees_department_id", "employees", ["department_id"], if_not_exists=True)
    op.create_index("ix_employees_reporting_manager_id", "employees", ["reporting_manager_id"], if_not_exists=True)
    op.create_index("ix_enterprise_audit_logs_actor_id", "enterprise_audit_logs", ["actor_id"], if_not_exists=True)
    op.create_index("ix_enterprise_audit_logs_clinic_id", "enterprise_audit_logs", ["clinic_id"], if_not_exists=True)
    op.create_index("ix_insurance_claims_invoice_id", "insurance_claims", ["invoice_id"], if_not_exists=True)
    op.create_index("ix_insurance_claims_policy_id", "insurance_claims", ["policy_id"], if_not_exists=True)
    op.create_index("ix_insurance_claims_preauth_id", "insurance_claims", ["preauth_id"], if_not_exists=True)
    op.create_index("ix_insurance_claims_treatment_id", "insurance_claims", ["treatment_id"], if_not_exists=True)
    op.create_index("ix_insurance_coverage_rules_clinic_id", "insurance_coverage_rules", ["clinic_id"], if_not_exists=True)
    op.create_index("ix_insurance_payment_reconciliations_invoice_id", "insurance_payment_reconciliations", ["invoice_id"], if_not_exists=True)
    op.create_index("ix_insurance_preauthorizations_policy_id", "insurance_preauthorizations", ["policy_id"], if_not_exists=True)
    op.create_index("ix_insurance_preauthorizations_treatment_id", "insurance_preauthorizations", ["treatment_id"], if_not_exists=True)
    op.create_index("ix_interview_schedules_applicant_id", "interview_schedules", ["applicant_id"], if_not_exists=True)
    op.create_index("ix_interview_schedules_interviewer_id", "interview_schedules", ["interviewer_id"], if_not_exists=True)
    op.create_index("ix_inventory_batches_item_id", "inventory_batches", ["item_id"], if_not_exists=True)
    op.create_index("ix_inventory_batches_supplier_id", "inventory_batches", ["supplier_id"], if_not_exists=True)
    op.create_index("ix_inventory_items_medicine_catalog_id", "inventory_items", ["medicine_catalog_id"], if_not_exists=True)
    op.create_index("ix_inventory_items_supplier_id", "inventory_items", ["supplier_id"], if_not_exists=True)
    op.create_index("ix_inventory_transfers_dispatched_by", "inventory_transfers", ["dispatched_by"], if_not_exists=True)
    op.create_index("ix_inventory_transfers_from_clinic_id", "inventory_transfers", ["from_clinic_id"], if_not_exists=True)
    op.create_index("ix_inventory_transfers_item_id", "inventory_transfers", ["item_id"], if_not_exists=True)
    op.create_index("ix_inventory_transfers_received_by", "inventory_transfers", ["received_by"], if_not_exists=True)
    op.create_index("ix_inventory_transfers_to_clinic_id", "inventory_transfers", ["to_clinic_id"], if_not_exists=True)
    op.create_index("ix_invoices_appointment_id", "invoices", ["appointment_id"], if_not_exists=True)
    op.create_index("ix_invoices_dentist_id", "invoices", ["dentist_id"], if_not_exists=True)
    op.create_index("ix_invoices_patient_id", "invoices", ["patient_id"], if_not_exists=True)
    op.create_index("ix_invoices_treatment_id", "invoices", ["treatment_id"], if_not_exists=True)
    op.create_index("ix_job_applicants_job_opening_id", "job_applicants", ["job_opening_id"], if_not_exists=True)
    op.create_index("ix_job_openings_clinic_id", "job_openings", ["clinic_id"], if_not_exists=True)
    op.create_index("ix_job_openings_department_id", "job_openings", ["department_id"], if_not_exists=True)
    op.create_index("ix_job_openings_organization_id", "job_openings", ["organization_id"], if_not_exists=True)
    op.create_index("ix_leave_requests_clinic_id", "leave_requests", ["clinic_id"], if_not_exists=True)
    op.create_index("ix_leave_requests_hr_id", "leave_requests", ["hr_id"], if_not_exists=True)
    op.create_index("ix_leave_requests_manager_id", "leave_requests", ["manager_id"], if_not_exists=True)
    op.create_index("ix_leave_requests_organization_id", "leave_requests", ["organization_id"], if_not_exists=True)
    op.create_index("ix_messages_sender_patient_id", "messages", ["sender_patient_id"], if_not_exists=True)
    op.create_index("ix_messages_sender_user_id", "messages", ["sender_user_id"], if_not_exists=True)
    op.create_index("ix_mobile_clinical_media_captured_by_id", "mobile_clinical_media", ["captured_by_id"], if_not_exists=True)
    op.create_index("ix_mobile_clinical_media_clinic_id", "mobile_clinical_media", ["clinic_id"], if_not_exists=True)
    op.create_index("ix_mobile_devices_clinic_id", "mobile_devices", ["clinic_id"], if_not_exists=True)
    op.create_index("ix_mobile_digital_signatures_clinic_id", "mobile_digital_signatures", ["clinic_id"], if_not_exists=True)
    op.create_index("ix_mobile_digital_signatures_patient_id", "mobile_digital_signatures", ["patient_id"], if_not_exists=True)
    op.create_index("ix_mobile_sync_queues_device_id", "mobile_sync_queues", ["device_id"], if_not_exists=True)
    op.create_index("ix_patient_forms_reviewed_by_id", "patient_forms", ["reviewed_by_id"], if_not_exists=True)
    op.create_index("ix_patient_forms_template_id", "patient_forms", ["template_id"], if_not_exists=True)
    op.create_index("ix_patient_insurance_policies_plan_id", "patient_insurance_policies", ["plan_id"], if_not_exists=True)
    op.create_index("ix_patient_insurance_policies_provider_id", "patient_insurance_policies", ["provider_id"], if_not_exists=True)
    op.create_index("ix_patient_insurance_policies_verified_by", "patient_insurance_policies", ["verified_by"], if_not_exists=True)
    op.create_index("ix_patient_merge_records_duplicate_patient_id", "patient_merge_records", ["duplicate_patient_id"], if_not_exists=True)
    op.create_index("ix_patient_merge_records_merged_by", "patient_merge_records", ["merged_by"], if_not_exists=True)
    op.create_index("ix_patient_merge_records_organization_id", "patient_merge_records", ["organization_id"], if_not_exists=True)
    op.create_index("ix_patient_merge_records_primary_patient_id", "patient_merge_records", ["primary_patient_id"], if_not_exists=True)
    op.create_index("ix_patient_timeline_events_actor_id", "patient_timeline_events", ["actor_id"], if_not_exists=True)
    op.create_index("ix_patient_transfers_approved_by", "patient_transfers", ["approved_by"], if_not_exists=True)
    op.create_index("ix_patient_transfers_from_clinic_id", "patient_transfers", ["from_clinic_id"], if_not_exists=True)
    op.create_index("ix_patient_transfers_initiated_by", "patient_transfers", ["initiated_by"], if_not_exists=True)
    op.create_index("ix_patient_transfers_to_clinic_id", "patient_transfers", ["to_clinic_id"], if_not_exists=True)
    op.create_index("ix_payments_received_by", "payments", ["received_by"], if_not_exists=True)
    op.create_index("ix_payments_refunded_by", "payments", ["refunded_by"], if_not_exists=True)
    op.create_index("ix_payroll_runs_approved_by", "payroll_runs", ["approved_by"], if_not_exists=True)
    op.create_index("ix_payroll_runs_clinic_id", "payroll_runs", ["clinic_id"], if_not_exists=True)
    op.create_index("ix_payroll_runs_organization_id", "payroll_runs", ["organization_id"], if_not_exists=True)
    op.create_index("ix_payslips_clinic_id", "payslips", ["clinic_id"], if_not_exists=True)
    op.create_index("ix_payslips_employee_id", "payslips", ["employee_id"], if_not_exists=True)
    op.create_index("ix_performance_reviews_clinic_id", "performance_reviews", ["clinic_id"], if_not_exists=True)
    op.create_index("ix_performance_reviews_employee_id", "performance_reviews", ["employee_id"], if_not_exists=True)
    op.create_index("ix_performance_reviews_organization_id", "performance_reviews", ["organization_id"], if_not_exists=True)
    op.create_index("ix_performance_reviews_reviewer_id", "performance_reviews", ["reviewer_id"], if_not_exists=True)
    op.create_index("ix_prescriptions_appointment_id", "prescriptions", ["appointment_id"], if_not_exists=True)
    op.create_index("ix_prescriptions_dentist_id", "prescriptions", ["dentist_id"], if_not_exists=True)
    op.create_index("ix_prescriptions_patient_id", "prescriptions", ["patient_id"], if_not_exists=True)
    op.create_index("ix_prescriptions_superseded_by_id", "prescriptions", ["superseded_by_id"], if_not_exists=True)
    op.create_index("ix_prescriptions_treatment_id", "prescriptions", ["treatment_id"], if_not_exists=True)
    op.create_index("ix_procedure_material_templates_item_id", "procedure_material_templates", ["item_id"], if_not_exists=True)
    op.create_index("ix_purchase_order_items_item_id", "purchase_order_items", ["item_id"], if_not_exists=True)
    op.create_index("ix_purchase_orders_approved_by", "purchase_orders", ["approved_by"], if_not_exists=True)
    op.create_index("ix_purchase_orders_supplier_id", "purchase_orders", ["supplier_id"], if_not_exists=True)
    op.create_index("ix_refresh_tokens_replaced_by_token_id", "refresh_tokens", ["replaced_by_token_id"], if_not_exists=True)
    op.create_index("ix_regions_regional_manager_id", "regions", ["regional_manager_id"], if_not_exists=True)
    op.create_index("ix_role_permission_mappings_permission_id", "role_permission_mappings", ["permission_id"], if_not_exists=True)
    op.create_index("ix_staff_schedules_chair_id", "staff_schedules", ["chair_id"], if_not_exists=True)
    op.create_index("ix_staff_schedules_organization_id", "staff_schedules", ["organization_id"], if_not_exists=True)
    op.create_index("ix_staff_schedules_shift_id", "staff_schedules", ["shift_id"], if_not_exists=True)
    op.create_index("ix_stock_transactions_actor_id", "stock_transactions", ["actor_id"], if_not_exists=True)
    op.create_index("ix_stock_transactions_batch_id", "stock_transactions", ["batch_id"], if_not_exists=True)
    op.create_index("ix_stock_transactions_item_id", "stock_transactions", ["item_id"], if_not_exists=True)
    op.create_index("ix_stock_transactions_related_invoice_id", "stock_transactions", ["related_invoice_id"], if_not_exists=True)
    op.create_index("ix_stock_transactions_related_po_id", "stock_transactions", ["related_po_id"], if_not_exists=True)
    op.create_index("ix_tooth_history_appointment_id", "tooth_history", ["appointment_id"], if_not_exists=True)
    op.create_index("ix_tooth_history_created_by", "tooth_history", ["created_by"], if_not_exists=True)
    op.create_index("ix_tooth_history_dentist_id", "tooth_history", ["dentist_id"], if_not_exists=True)
    op.create_index("ix_tooth_history_patient_id", "tooth_history", ["patient_id"], if_not_exists=True)
    op.create_index("ix_tooth_history_tooth_id", "tooth_history", ["tooth_id"], if_not_exists=True)
    op.create_index("ix_tooth_history_treatment_id", "tooth_history", ["treatment_id"], if_not_exists=True)
    op.create_index("ix_tooth_history_treatment_procedure_id", "tooth_history", ["treatment_procedure_id"], if_not_exists=True)
    op.create_index("ix_tooth_surfaces_dentist_id", "tooth_surfaces", ["dentist_id"], if_not_exists=True)
    op.create_index("ix_training_courses_organization_id", "training_courses", ["organization_id"], if_not_exists=True)
    op.create_index("ix_treatment_follow_ups_patient_id", "treatment_follow_ups", ["patient_id"], if_not_exists=True)
    op.create_index("ix_treatments_patient_id", "treatments", ["patient_id"], if_not_exists=True)
    op.create_index("ix_user_branch_assignments_clinic_id", "user_branch_assignments", ["clinic_id"], if_not_exists=True)
    op.create_index("ix_user_permission_overrides_permission_id", "user_permission_overrides", ["permission_id"], if_not_exists=True)
    op.create_index("ix_work_shifts_clinic_id", "work_shifts", ["clinic_id"], if_not_exists=True)
    op.create_index("ix_work_shifts_organization_id", "work_shifts", ["organization_id"], if_not_exists=True)


def downgrade() -> None:
    op.drop_index("ix_work_shifts_organization_id", table_name="work_shifts", if_exists=True)
    op.drop_index("ix_work_shifts_clinic_id", table_name="work_shifts", if_exists=True)
    op.drop_index("ix_user_permission_overrides_permission_id", table_name="user_permission_overrides", if_exists=True)
    op.drop_index("ix_user_branch_assignments_clinic_id", table_name="user_branch_assignments", if_exists=True)
    op.drop_index("ix_treatments_patient_id", table_name="treatments", if_exists=True)
    op.drop_index("ix_treatment_follow_ups_patient_id", table_name="treatment_follow_ups", if_exists=True)
    op.drop_index("ix_training_courses_organization_id", table_name="training_courses", if_exists=True)
    op.drop_index("ix_tooth_surfaces_dentist_id", table_name="tooth_surfaces", if_exists=True)
    op.drop_index("ix_tooth_history_treatment_procedure_id", table_name="tooth_history", if_exists=True)
    op.drop_index("ix_tooth_history_treatment_id", table_name="tooth_history", if_exists=True)
    op.drop_index("ix_tooth_history_tooth_id", table_name="tooth_history", if_exists=True)
    op.drop_index("ix_tooth_history_patient_id", table_name="tooth_history", if_exists=True)
    op.drop_index("ix_tooth_history_dentist_id", table_name="tooth_history", if_exists=True)
    op.drop_index("ix_tooth_history_created_by", table_name="tooth_history", if_exists=True)
    op.drop_index("ix_tooth_history_appointment_id", table_name="tooth_history", if_exists=True)
    op.drop_index("ix_stock_transactions_related_po_id", table_name="stock_transactions", if_exists=True)
    op.drop_index("ix_stock_transactions_related_invoice_id", table_name="stock_transactions", if_exists=True)
    op.drop_index("ix_stock_transactions_item_id", table_name="stock_transactions", if_exists=True)
    op.drop_index("ix_stock_transactions_batch_id", table_name="stock_transactions", if_exists=True)
    op.drop_index("ix_stock_transactions_actor_id", table_name="stock_transactions", if_exists=True)
    op.drop_index("ix_staff_schedules_shift_id", table_name="staff_schedules", if_exists=True)
    op.drop_index("ix_staff_schedules_organization_id", table_name="staff_schedules", if_exists=True)
    op.drop_index("ix_staff_schedules_chair_id", table_name="staff_schedules", if_exists=True)
    op.drop_index("ix_role_permission_mappings_permission_id", table_name="role_permission_mappings", if_exists=True)
    op.drop_index("ix_regions_regional_manager_id", table_name="regions", if_exists=True)
    op.drop_index("ix_refresh_tokens_replaced_by_token_id", table_name="refresh_tokens", if_exists=True)
    op.drop_index("ix_purchase_orders_supplier_id", table_name="purchase_orders", if_exists=True)
    op.drop_index("ix_purchase_orders_approved_by", table_name="purchase_orders", if_exists=True)
    op.drop_index("ix_purchase_order_items_item_id", table_name="purchase_order_items", if_exists=True)
    op.drop_index("ix_procedure_material_templates_item_id", table_name="procedure_material_templates", if_exists=True)
    op.drop_index("ix_prescriptions_treatment_id", table_name="prescriptions", if_exists=True)
    op.drop_index("ix_prescriptions_superseded_by_id", table_name="prescriptions", if_exists=True)
    op.drop_index("ix_prescriptions_patient_id", table_name="prescriptions", if_exists=True)
    op.drop_index("ix_prescriptions_dentist_id", table_name="prescriptions", if_exists=True)
    op.drop_index("ix_prescriptions_appointment_id", table_name="prescriptions", if_exists=True)
    op.drop_index("ix_performance_reviews_reviewer_id", table_name="performance_reviews", if_exists=True)
    op.drop_index("ix_performance_reviews_organization_id", table_name="performance_reviews", if_exists=True)
    op.drop_index("ix_performance_reviews_employee_id", table_name="performance_reviews", if_exists=True)
    op.drop_index("ix_performance_reviews_clinic_id", table_name="performance_reviews", if_exists=True)
    op.drop_index("ix_payslips_employee_id", table_name="payslips", if_exists=True)
    op.drop_index("ix_payslips_clinic_id", table_name="payslips", if_exists=True)
    op.drop_index("ix_payroll_runs_organization_id", table_name="payroll_runs", if_exists=True)
    op.drop_index("ix_payroll_runs_clinic_id", table_name="payroll_runs", if_exists=True)
    op.drop_index("ix_payroll_runs_approved_by", table_name="payroll_runs", if_exists=True)
    op.drop_index("ix_payments_refunded_by", table_name="payments", if_exists=True)
    op.drop_index("ix_payments_received_by", table_name="payments", if_exists=True)
    op.drop_index("ix_patient_transfers_to_clinic_id", table_name="patient_transfers", if_exists=True)
    op.drop_index("ix_patient_transfers_initiated_by", table_name="patient_transfers", if_exists=True)
    op.drop_index("ix_patient_transfers_from_clinic_id", table_name="patient_transfers", if_exists=True)
    op.drop_index("ix_patient_transfers_approved_by", table_name="patient_transfers", if_exists=True)
    op.drop_index("ix_patient_timeline_events_actor_id", table_name="patient_timeline_events", if_exists=True)
    op.drop_index("ix_patient_merge_records_primary_patient_id", table_name="patient_merge_records", if_exists=True)
    op.drop_index("ix_patient_merge_records_organization_id", table_name="patient_merge_records", if_exists=True)
    op.drop_index("ix_patient_merge_records_merged_by", table_name="patient_merge_records", if_exists=True)
    op.drop_index("ix_patient_merge_records_duplicate_patient_id", table_name="patient_merge_records", if_exists=True)
    op.drop_index("ix_patient_insurance_policies_verified_by", table_name="patient_insurance_policies", if_exists=True)
    op.drop_index("ix_patient_insurance_policies_provider_id", table_name="patient_insurance_policies", if_exists=True)
    op.drop_index("ix_patient_insurance_policies_plan_id", table_name="patient_insurance_policies", if_exists=True)
    op.drop_index("ix_patient_forms_template_id", table_name="patient_forms", if_exists=True)
    op.drop_index("ix_patient_forms_reviewed_by_id", table_name="patient_forms", if_exists=True)
    op.drop_index("ix_mobile_sync_queues_device_id", table_name="mobile_sync_queues", if_exists=True)
    op.drop_index("ix_mobile_digital_signatures_patient_id", table_name="mobile_digital_signatures", if_exists=True)
    op.drop_index("ix_mobile_digital_signatures_clinic_id", table_name="mobile_digital_signatures", if_exists=True)
    op.drop_index("ix_mobile_devices_clinic_id", table_name="mobile_devices", if_exists=True)
    op.drop_index("ix_mobile_clinical_media_clinic_id", table_name="mobile_clinical_media", if_exists=True)
    op.drop_index("ix_mobile_clinical_media_captured_by_id", table_name="mobile_clinical_media", if_exists=True)
    op.drop_index("ix_messages_sender_user_id", table_name="messages", if_exists=True)
    op.drop_index("ix_messages_sender_patient_id", table_name="messages", if_exists=True)
    op.drop_index("ix_leave_requests_organization_id", table_name="leave_requests", if_exists=True)
    op.drop_index("ix_leave_requests_manager_id", table_name="leave_requests", if_exists=True)
    op.drop_index("ix_leave_requests_hr_id", table_name="leave_requests", if_exists=True)
    op.drop_index("ix_leave_requests_clinic_id", table_name="leave_requests", if_exists=True)
    op.drop_index("ix_job_openings_organization_id", table_name="job_openings", if_exists=True)
    op.drop_index("ix_job_openings_department_id", table_name="job_openings", if_exists=True)
    op.drop_index("ix_job_openings_clinic_id", table_name="job_openings", if_exists=True)
    op.drop_index("ix_job_applicants_job_opening_id", table_name="job_applicants", if_exists=True)
    op.drop_index("ix_invoices_treatment_id", table_name="invoices", if_exists=True)
    op.drop_index("ix_invoices_patient_id", table_name="invoices", if_exists=True)
    op.drop_index("ix_invoices_dentist_id", table_name="invoices", if_exists=True)
    op.drop_index("ix_invoices_appointment_id", table_name="invoices", if_exists=True)
    op.drop_index("ix_inventory_transfers_to_clinic_id", table_name="inventory_transfers", if_exists=True)
    op.drop_index("ix_inventory_transfers_received_by", table_name="inventory_transfers", if_exists=True)
    op.drop_index("ix_inventory_transfers_item_id", table_name="inventory_transfers", if_exists=True)
    op.drop_index("ix_inventory_transfers_from_clinic_id", table_name="inventory_transfers", if_exists=True)
    op.drop_index("ix_inventory_transfers_dispatched_by", table_name="inventory_transfers", if_exists=True)
    op.drop_index("ix_inventory_items_supplier_id", table_name="inventory_items", if_exists=True)
    op.drop_index("ix_inventory_items_medicine_catalog_id", table_name="inventory_items", if_exists=True)
    op.drop_index("ix_inventory_batches_supplier_id", table_name="inventory_batches", if_exists=True)
    op.drop_index("ix_inventory_batches_item_id", table_name="inventory_batches", if_exists=True)
    op.drop_index("ix_interview_schedules_interviewer_id", table_name="interview_schedules", if_exists=True)
    op.drop_index("ix_interview_schedules_applicant_id", table_name="interview_schedules", if_exists=True)
    op.drop_index("ix_insurance_preauthorizations_treatment_id", table_name="insurance_preauthorizations", if_exists=True)
    op.drop_index("ix_insurance_preauthorizations_policy_id", table_name="insurance_preauthorizations", if_exists=True)
    op.drop_index("ix_insurance_payment_reconciliations_invoice_id", table_name="insurance_payment_reconciliations", if_exists=True)
    op.drop_index("ix_insurance_coverage_rules_clinic_id", table_name="insurance_coverage_rules", if_exists=True)
    op.drop_index("ix_insurance_claims_treatment_id", table_name="insurance_claims", if_exists=True)
    op.drop_index("ix_insurance_claims_preauth_id", table_name="insurance_claims", if_exists=True)
    op.drop_index("ix_insurance_claims_policy_id", table_name="insurance_claims", if_exists=True)
    op.drop_index("ix_insurance_claims_invoice_id", table_name="insurance_claims", if_exists=True)
    op.drop_index("ix_enterprise_audit_logs_clinic_id", table_name="enterprise_audit_logs", if_exists=True)
    op.drop_index("ix_enterprise_audit_logs_actor_id", table_name="enterprise_audit_logs", if_exists=True)
    op.drop_index("ix_employees_reporting_manager_id", table_name="employees", if_exists=True)
    op.drop_index("ix_employees_department_id", table_name="employees", if_exists=True)
    op.drop_index("ix_employees_clinic_id", table_name="employees", if_exists=True)
    op.drop_index("ix_employee_training_records_employee_id", table_name="employee_training_records", if_exists=True)
    op.drop_index("ix_employee_training_records_course_id", table_name="employee_training_records", if_exists=True)
    op.drop_index("ix_employee_incentives_employee_id", table_name="employee_incentives", if_exists=True)
    op.drop_index("ix_employee_incentives_approved_by", table_name="employee_incentives", if_exists=True)
    op.drop_index("ix_employee_documents_employee_id", table_name="employee_documents", if_exists=True)
    op.drop_index("ix_departments_head_dentist_id", table_name="departments", if_exists=True)
    op.drop_index("ix_attendance_records_organization_id", table_name="attendance_records", if_exists=True)
    op.drop_index("ix_attendance_records_clinic_id", table_name="attendance_records", if_exists=True)
    op.drop_index("ix_appointments_rescheduled_from_id", table_name="appointments", if_exists=True)
    op.drop_index("ix_appointment_timeline_events_actor_id", table_name="appointment_timeline_events", if_exists=True)
    op.drop_index("ix_ai_recommendations_treatment_id", table_name="ai_recommendations", if_exists=True)
    op.drop_index("ix_ai_recommendations_reviewed_by_id", table_name="ai_recommendations", if_exists=True)
    op.drop_index("ix_ai_recommendations_dentist_id", table_name="ai_recommendations", if_exists=True)
    op.drop_index("ix_ai_recommendations_appointment_id", table_name="ai_recommendations", if_exists=True)
    op.drop_index("ix_ai_audit_logs_user_id", table_name="ai_audit_logs", if_exists=True)
    op.drop_index("ix_ai_audit_logs_patient_id", table_name="ai_audit_logs", if_exists=True)
